# Dockerfile for a Python Application Development Environment
# Author: Patryk Golabek
# Copyright: Translucent Computing Inc. 2023

# Define the Python version to use at build time. Default is set to 3.9
ARG PYTHON_VERSION=3.9

# Use the Python version as defined in PYTHON_VERSION
FROM python:${PYTHON_VERSION}

LABEL maintainer="Patryk Golabek <patryk@translucentcomputing.com>"

# Install necessary packages - Versions pinned to Debian Bullseye
RUN apt-get update && apt-get install -y --no-install-recommends \
    tini=0.19.0-1 \
    curl=7.74.0-1.3+deb11u10 \
    wget=1.21-1+deb11u1 \
    bash=5.1-2+deb11u1 \
    inetutils-ping=2:2.0-1+deb11u2 \
    dnsutils=1:9.16.44-1~deb11u1 \
    git=1:2.30.2-1+deb11u2 \
    openssl=1.1.1w-0+deb11u1 \
    redis-tools=5:6.0.16-1+deb11u2 \
    make=4.3-4.1 && \
    rm -rf /var/lib/apt/lists/*

# Prepare the app directory
# Set an environment variable with the directory where we'll be running the app.
ENV APP /app
RUN mkdir $APP
WORKDIR $APP

# Use tini as the default entrypoint to handle signals and zombie processes
ENTRYPOINT ["/usr/bin/tini", "--"]
