theme: jekyll-theme-rtd
title: Slack Bot For Kubernetes
description: This project demonstrates how to use DevSpace and develop Slack Bot with Slack Bolt framework and FastAPI web framework. With deployment to the Kubernetes cluster.
search_enabled: true
sticky_navigation: true
prev_next_buttons_location: None
edit_on_github: false
site_author: TC Team
github_docs_folder: true
repo_url: "https://github.com/TranslucentComputing/webinar-slack-bot"
hljs_style: github-gist
logo: "https://www.translucentcomputing.com/wp-content/uploads/2022/05/logo.svg"
